include:
 - docker-compose.dependencies.yml
  
services:
  monkeyApi:
    build:
      context: .
      dockerfile: src/MonkeyShelter.Api/Dockerfile
    image: monkeyshelter-api:latest
    ports:
      - "5242:5242"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=monkeyservice;Username=user;Password=pass;
      - ConnectionStrings__RabbitMq=rabbitmq://rabbitmq:5672
    depends_on:
      postgres:
        condition: service_healthy
      
  monkeyAuth:
    build:
      context: ./src/MonkeyShelter.Auth/
      dockerfile: Dockerfile
    image: monkeyshelter-auth:latest
    ports:
      - "5270:5270"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=monkeyauth;Username=user;Password=pass;
      - ConnectionStrings__RabbitMq=rabbitmq://rabbitmq:5672
      
  vet-scheduler:
    build:
      context: .
      dockerfile: src/MonkeyShelter.Worker.VetScheduler/Dockerfile
    depends_on:
    rabbitmq:
      condition: service_healthy
    postgres:
      condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=monkeyservice;Username=user;Password=pass;
      - ConnectionStrings__RabbitMq=rabbitmq://rabbitmq:5672
