include:
 - docker-compose.dependencies.yml
  
services:
  api:
    build:
      context: .
      dockerfile: src/MonkeyShelter.Api/Dockerfile
    image: monkeyshelter-api:latest
    ports:
      - "5242:5242"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=monkeyservice;Username=user;Password=pass;
      - ConnectionStrings__RabbitMq=rabbitmq://rabbitmq:5672
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5242
    depends_on:
      postgres:
        condition: service_healthy

  monkeyAuth:
    build:
      context: .
      dockerfile: src/MonkeyShelter.Auth/Dockerfile
    image: monkeyshelter-auth:latest
    ports:
      - "5270:5270"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=monkeyauth;Username=user;Password=pass;
      - ConnectionStrings__RabbitMq=rabbitmq://rabbitmq:5672
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5270
    depends_on:
      postgres:
        condition: service_healthy

  vet-scheduler:
    build:
      context: .
      dockerfile: src/MonkeyShelter.Worker.VetScheduler/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=monkeyservice;Username=user;Password=pass;
      - RabbitMq__Host=rabbitmq://rabbitmq:5672
      - RabbitMq__Username=user
      - RabbitMq__Password=pass
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      api:
        condition: service_started
        
  audit:
    build:
      context: .
      dockerfile: src/MonkeyShelter.Audit/Dockerfile
    image: monkeyshelter-audit:latest
    environment:
      - ConnectionStrings__AuditDatabase=Host=postgres;Port=5432;Database=monkeyaudit;Username=user;Password=pass;
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMq__Host=rabbitmq://rabbitmq:5672
      - RabbitMq__Username=user
      - RabbitMq__Password=pass
    depends_on:
      postgres:
        condition: service_healthy

  reports:
    build:
      context: .
      dockerfile: src/MonkeyShelter.Reports/Dockerfile
    image: monkeyshelter-reports:latest
    ports:
      - "5109:5109"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=monkeyservice;Username=user;Password=pass;
      - ConnectionStrings__Redis=redis:6379
      - RabbitMq__Host=rabbitmq://rabbitmq:5672
      - RabbitMq__Username=user
      - RabbitMq__Password=pass
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5109
    depends_on:
      - postgres
      - redis
      - rabbitmq

volumes:
  postgres-data:
  redis-data:
